import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "@/app/globals.css";

const ibm = IBM_Plex_Mono({
  weight: ["100", "200", "300", "400", "700", ], 
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ibm.className}>{children}</body>
    </html>
  );
}
